development:
  adapter: postgresql
  encoding: unicode
  database: s3_direct_upload_development
  host: localhost
  pool: 5
  username: postgres
  password: pinak

test:
  adapter: postgresql
  encoding: unicode
  database: s3_direct_upload_test
  host: localhost
  pool: 5
  username: postgres
  password: pinak
